apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: search
        image: asia-east1-docker.pkg.dev/$PROJECT_ID/ann/search:$SHORT_SHA
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: search-env
              key: DATABASE_URL
        - name: SOURCE_DIR
          valueFrom:
            secretKeyRef:
              name: search-env
              key: SOURCE_DIR
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: search-env 
              key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: search
spec:
  selector:
    app: search
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    