"""generate db

Revision ID: 17d20a25d9b5
Revises: 
Create Date: 2026-01-20 09:22:31.717636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d20a25d9b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyze',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('whisper_text', sa.Text(), nullable=True),
    sa.Column('llm_text', sa.Text(), nullable=True),
    sa.Column('ground_truth', sa.Text(), nullable=True),
    sa.Column('whisper_wer', sa.Float(), nullable=True),
    sa.Column('llm_wer', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyze')),
    sa.UniqueConstraint('file_path', name=op.f('uq_analyze_file_path'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyze')
    # ### end Alembic commands ###
