"""add text_with_rag field

Revision ID: 258c16e2ecf2
Revises: c9edc01912c8
Create Date: 2026-01-24 11:47:25.056993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258c16e2ecf2'
down_revision: Union[str, Sequence[str], None] = 'c9edc01912c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_outputs', sa.Column('text_with_rag', sa.Text(), nullable=True))
    op.alter_column('llm_outputs', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_outputs', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('llm_outputs', 'text_with_rag')
    # ### end Alembic commands ###
