"""add mts

Revision ID: 2e12c1dd1b41
Revises: d715db1890f9
Create Date: 2026-01-28 15:41:31.802963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e12c1dd1b41'
down_revision: Union[str, Sequence[str], None] = 'd715db1890f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('llm_mts_wer', sa.Float(), nullable=True))
    op.add_column('llm_outputs', sa.Column('text_with_mts', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_outputs', 'text_with_mts')
    op.drop_column('evaluations', 'llm_mts_wer')
    # ### end Alembic commands ###
