"""modify llm with agent

Revision ID: 3ec98db617e0
Revises: d44a8f15441a
Create Date: 2026-01-28 10:42:44.981161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec98db617e0'
down_revision: Union[str, Sequence[str], None] = 'd44a8f15441a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('llm_agent_tool1_wer', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('llm_agent_tool1_tool2_wer', sa.Float(), nullable=True))
    op.drop_column('evaluations', 'llm_rag_wer')
    op.add_column('llm_outputs', sa.Column('text_agent_tool1', sa.Text(), nullable=True))
    op.add_column('llm_outputs', sa.Column('text_agent_tool1_tool2', sa.Text(), nullable=True))
    op.drop_column('llm_outputs', 'text_with_rag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_outputs', sa.Column('text_with_rag', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('llm_outputs', 'text_agent_tool1_tool2')
    op.drop_column('llm_outputs', 'text_agent_tool1')
    op.add_column('evaluations', sa.Column('llm_rag_wer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('evaluations', 'llm_agent_tool1_tool2_wer')
    op.drop_column('evaluations', 'llm_agent_tool1_wer')
    # ### end Alembic commands ###
