"""cloud transcription

Revision ID: 4b547a9c43a3
Revises: b84ce98cc940
Create Date: 2026-02-03 13:54:40.094076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b547a9c43a3'
down_revision: Union[str, Sequence[str], None] = 'b84ce98cc940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_outputs', sa.Column('text_with_google', sa.Text(), nullable=True))
    op.add_column('llm_outputs', sa.Column('text_with_aws', sa.Text(), nullable=True))
    op.add_column('llm_outputs', sa.Column('text_with_dr_ai', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_outputs', 'text_with_dr_ai')
    op.drop_column('llm_outputs', 'text_with_aws')
    op.drop_column('llm_outputs', 'text_with_google')
    # ### end Alembic commands ###
