"""add hematology

Revision ID: 76c4b1339373
Revises: 2e12c1dd1b41
Create Date: 2026-01-29 11:32:00.112361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76c4b1339373'
down_revision: Union[str, Sequence[str], None] = '2e12c1dd1b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('llm_hematology_wer', sa.Float(), nullable=True))
    op.drop_column('evaluations', 'llm_mts_wer')
    op.add_column('llm_outputs', sa.Column('text_with_hematology', sa.Text(), nullable=True))
    op.drop_column('llm_outputs', 'text_with_mts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_outputs', sa.Column('text_with_mts', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('llm_outputs', 'text_with_hematology')
    op.add_column('evaluations', sa.Column('llm_mts_wer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('evaluations', 'llm_hematology_wer')
    # ### end Alembic commands ###
