"""create analyze table

Revision ID: 7a8ab27fd7bd
Revises: 
Create Date: 2025-06-09 10:57:55.410713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8ab27fd7bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyze',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('whisper_text', sa.Text(), nullable=True),
    sa.Column('llm_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyze')),
    sa.UniqueConstraint('file_path', name=op.f('uq_analyze_file_path'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyze')
    # ### end Alembic commands ###
