"""add word error rate

Revision ID: a4909f079f8d
Revises: bf05f2fcc590
Create Date: 2025-06-09 14:02:20.975942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4909f079f8d'
down_revision: Union[str, None] = 'bf05f2fcc590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyze', sa.Column('whisper_wer', sa.Float(), nullable=True))
    op.add_column('analyze', sa.Column('llm_wer', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyze', 'llm_wer')
    op.drop_column('analyze', 'whisper_wer')
    # ### end Alembic commands ###
