"""analyze modify

Revision ID: bf05f2fcc590
Revises: 7a8ab27fd7bd
Create Date: 2025-06-09 11:53:03.911014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf05f2fcc590'
down_revision: Union[str, None] = '7a8ab27fd7bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyze', sa.Column('ground_truth', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyze', 'ground_truth')
    # ### end Alembic commands ###
