"""new analyze models

Revision ID: c9edc01912c8
Revises: 
Create Date: 2026-01-21 08:58:38.440190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9edc01912c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_files')),
    sa.UniqueConstraint('file_path', name=op.f('uq_audio_files_file_path'))
    )
    op.create_table('llm_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('quantization', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_models')),
    sa.UniqueConstraint('name', name=op.f('uq_llm_models_name'))
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_file_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], name=op.f('fk_transcriptions_audio_file_id_audio_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcriptions'))
    )
    op.create_table('llm_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcription_id', sa.Integer(), nullable=False),
    sa.Column('llm_model_id', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], name=op.f('fk_llm_outputs_llm_model_id_llm_models')),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], name=op.f('fk_llm_outputs_transcription_id_transcriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_outputs'))
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm_output_id', sa.Integer(), nullable=False),
    sa.Column('ground_truth', sa.Text(), nullable=True),
    sa.Column('whisper_wer', sa.Float(), nullable=True),
    sa.Column('llm_wer', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['llm_output_id'], ['llm_outputs.id'], name=op.f('fk_evaluations_llm_output_id_llm_outputs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    op.drop_table('llm_outputs')
    op.drop_table('transcriptions')
    op.drop_table('llm_models')
    op.drop_table('audio_files')
    # ### end Alembic commands ###
