"""add agent

Revision ID: d1a7eddcdcf2
Revises: a1b2c3d4e5f6
Create Date: 2026-02-02 15:01:35.598107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a7eddcdcf2'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('llm_agent_wer', sa.Float(), nullable=True))
    op.add_column('llm_outputs', sa.Column('text_agent', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_outputs', 'text_agent')
    op.drop_column('evaluations', 'llm_agent_wer')
    # ### end Alembic commands ###
