"""add llm_with_rag wer

Revision ID: d44a8f15441a
Revises: 258c16e2ecf2
Create Date: 2026-01-26 09:11:17.500046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44a8f15441a'
down_revision: Union[str, Sequence[str], None] = '258c16e2ecf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('llm_rag_wer', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'llm_rag_wer')
    # ### end Alembic commands ###
