"""modify only with rag

Revision ID: d715db1890f9
Revises: 3ec98db617e0
Create Date: 2026-01-28 13:42:47.490284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd715db1890f9'
down_revision: Union[str, Sequence[str], None] = '3ec98db617e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('llm_rag_wer', sa.Float(), nullable=True))
    op.drop_column('evaluations', 'llm_agent_tool1_tool2_wer')
    op.drop_column('evaluations', 'llm_agent_tool1_wer')
    op.add_column('llm_outputs', sa.Column('text_with_rag', sa.Text(), nullable=True))
    op.drop_column('llm_outputs', 'text_agent_tool1_tool2')
    op.drop_column('llm_outputs', 'text_agent_tool1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_outputs', sa.Column('text_agent_tool1', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('llm_outputs', sa.Column('text_agent_tool1_tool2', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('llm_outputs', 'text_with_rag')
    op.add_column('evaluations', sa.Column('llm_agent_tool1_wer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('evaluations', sa.Column('llm_agent_tool1_tool2_wer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('evaluations', 'llm_rag_wer')
    # ### end Alembic commands ###
