"""add wer statistics

Revision ID: d9607164990a
Revises: 4b547a9c43a3
Create Date: 2026-02-06 11:05:00.221655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9607164990a'
down_revision: Union[str, Sequence[str], None] = '4b547a9c43a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wer_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_evaluations', sa.Integer(), nullable=True),
    sa.Column('avg_whisper_wer', sa.Float(), nullable=True),
    sa.Column('avg_llm_wer', sa.Float(), nullable=True),
    sa.Column('avg_llm_rag_wer', sa.Float(), nullable=True),
    sa.Column('avg_llm_hematology_wer', sa.Float(), nullable=True),
    sa.Column('avg_llm_agent_wer', sa.Float(), nullable=True),
    sa.Column('count_whisper_wer', sa.Integer(), nullable=True),
    sa.Column('count_llm_wer', sa.Integer(), nullable=True),
    sa.Column('count_llm_rag_wer', sa.Integer(), nullable=True),
    sa.Column('count_llm_hematology_wer', sa.Integer(), nullable=True),
    sa.Column('count_llm_agent_wer', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wer_statistics'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wer_statistics')
    # ### end Alembic commands ###
